### ISSUE TITLE
Suggest to loosen the dependency on mongoengine

### ISSUE THREAD

**Issue by Agnes-U** [rebase-network/rostra-backend#3]
Hi, your project rostra-backend(commit id: 3ac717eb567ef7dad325a3b8000753fefdbbef94) requires "mongoengine==0.23.1" in its dependency. After analyzing the source code, we found that the following versions of mongoengine can also be suitable, i.e., mongoengine 0.22.0, 0.22.1, 0.23.0, 0.24.0, 0.24.1, since all functions that you directly (8 APIs: mongoengine.document.EmbeddedDocument.__init__, mongoengine.fields.ListField.__init__, mongoengine.fields.IntField.__init__, mongoengine.document.Document.__init__, mongoengine.fields.StringField.__init__, mongoengine.fields.ReferenceField.__init__, mongoengine.fields.BooleanField.__init__, mongoengine.fields.EmbeddedDocumentField.__init__) or indirectly (propagate to 10 mongoengine's internal APIs and 3 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on mongoengine from "mongoengine==0.23.1" to "mongoengine>=0.22.0,<=0.24.1". This will improve the applicability of rostra-backend and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on mongoengine?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by luckyyang** [comment]
Thanks for your suggestion, however this project is not maintained.
